### ISSUE TITLE
OverflowException for any larger Wad files

### ISSUE THREAD

**Issue by RingtailRaider** [BuilderDemo7/WADExplorer#1]
I keep getting overflow issues depending on the size of the Wad file, I tried several from different DDI games (Tonka Space Station PC, Ninjabread Man PS2, My Personal Golf Trainer, etc),  and it seems ones under 30 MB load fine but ones over 50 MB will always fail to load (MPGT's Wad in particular is huge at 560 MB). When loading I get this error:

`The file (0x0000/0x68656361) has failed to load it's [sic] buffer Expect some errors for now on!`

and then it gives me a long error text, here's the beginning part from it"

`************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at WADExplorer.PackageOld.Load(Stream s) in D:\Monster Trux Extreme\Tools\WADExplorer\WADExplorer\REWAD\Package.cs:line 607
   at WADExplorer.Window.openToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Monster Trux Extreme\Tools\WADExplorer\WADExplorer\Window.cs:line 629
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Also when and how exactly did the DDI Wad format change? I know about three different versions of it: the original from Conquest Earth, the WWAD format from Lego Rock Raiders and Gubble Buggy, and the WADH format from Tonka Space Station onward (and also some various PSX ones used in only a few games). I wasn't aware of the WADH format changing at any point though.

**Comment by BuilderDemo7** [comment]
Hi, 

I'm sorry for taking so long to respond because I've forgot about this program for some time, 

are you saying there is a version out of the DDI Wad files that is new? Probably, but WADExplorer probably can't load these versions yet because WADExplorer can only load 2 versions of WAD files and I bet it could be a version that wasn't implemented and that I didn't know about.

I only reversed-engineered the versions of the WAD from Ninjabread Man, Monster Trux Extreme and Rig Racer 2.

**Comment by RingtailRaider** [comment]
hello, sorry I didn't see your response. What exactly was different between the wad formats in those games, and when did it change? I'm trying to learn how the DDI Wad (WADH) files work but wasn't aware of that, I'm more familiar with the format they used in Lego Rock Raiders (WWAD) which is completely different.
I'm not sure if this error would've been caused by that or was just an overflow issue since the file size seemed to be a consistent factor.

**Comment by BuilderDemo7** [comment]
Well, it was probably caused by the format that then caused the overflow issue.
